# Generated by Django 4.2.3 on 2023-08-11 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.IntegerField()),
                ('option_one', models.CharField(blank=True, max_length=200)),
                ('option_two', models.CharField(blank=True, max_length=200)),
                ('option_three', models.CharField(blank=True, max_length=200)),
                ('option_four', models.CharField(blank=True, max_length=200)),
                ('option_five', models.CharField(blank=True, max_length=200)),
                ('question_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.coursename')),
            ],
        ),
    ]
