# Generated by Django 4.2.4 on 2023-08-12 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.DurationField(default=datetime.timedelta(seconds=600)),
        ),
    ]
